Portfolio/portfolio_app/urls.py
from django.urls import include, path

from portfolio_app import admin
from . import views

urlpatterns = [
#path function defines a url pattern
#'' is empty to represent based path to app
# views.index is the function defined in views.py
# name='index' parameter is to dynamically create url
# example in html <a href="{% url 'index' %}">Home</a>.
    path('', views.index, name='index'),
    path('students/', views.StudentListView.as_view(), name='student'),
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('project/<int:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('portfolio/<int:portfolio_id>/create_project', views.createProject, name='create_project'),
    path('project/<int:project_id>/edit_project', views.editProject, name='edit_project'),
    path('portfolio/<int:portfolio_id>/update_portfolio', views.update_portfolio, name='update_portfolio'),
    path('project/int:<project_id>/delete_project', views.delete_project, name='delete_project'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.registerPage, name='register_page'),
    path('user/', views.userPage, name='user_page'),
]

Portfolio/portfolio_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Portfolio(models.Model):
    title = models.CharField(max_length=200, null=True)
    contact_email = models.CharField(max_length=200, null=True)
    is_active = models.BooleanField(default=False)
    about = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("portfolio-detail", args=[str(self.id)])

class Student(models.Model):

#List of choices for major value in database, human readable name
    MAJOR = (
    ('CSCI-BS', 'BS in Computer Science'),
    ('CPEN-BS', 'BS in Computer Engineering'),
    ('BIGD-BI', 'BI in Game Design and Development'),
    ('BICS-BI', 'BI in Computer Science'),
    ('BISC-BI', 'BI in Computer Security'),
    ('CSCI-BA', 'BA in Computer Science'),
    ('DASE-BS', 'BS in Data Analytics and Systems Engineering')
)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField("UCCS Email", max_length=200, null=True)
    major = models.CharField(max_length=200, choices=MAJOR, blank = False, null=True)
    portfolio = models.OneToOneField(Portfolio, null=True, on_delete=models.CASCADE, unique=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("student-detail", args=[str(self.id)])


class Project(models.Model):
    title = models.CharField(max_length=200, null=True)
    description = models.TextField(blank=False, null=True)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("project-detail", args=[str(self.id)])

Portfolio/portfolio_app/forms.py
from django.forms import ModelForm
from .models import Project, Portfolio, Student
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description',)

class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = ('title', 'contact_email', 'is_active', 'about')

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude =['user', 'portfolio']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Portfolio/portfolio_app/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import *
from .forms import ProjectForm, PortfolioForm, CreateUserForm, StudentForm
from django.views import generic
from django.contrib.auth.models import Group
from django.contrib import messages


# Create your views here.
def index(request):

# Render the HTML template index.html with the data in the context variable.
    studentActivePortfolios = Student.objects.select_related('portfolio').all().filter(portfolio__is_active=True)
    print("active portfolio query set", studentActivePortfolios)
    return render(request, 'portfolio_app/index.html', {'studentActivePortfolios': studentActivePortfolios})
  # return render( request, 'portfolio_app/index.html')

class StudentListView(generic.ListView):
    model = Student

class StudentDetailView(generic.DetailView):
    model = Student

class PortfolioDetailView(generic.DetailView):
    model = Portfolio

class ProjectListView(generic.ListView):
    model = Project

class ProjectDetailView(generic.DetailView):
    model = Project

def createProject(request, portfolio_id):
    form = ProjectForm()
    portfolio = Portfolio.objects.get(pk=portfolio_id)

    if request.method == 'POST':
        project_data = request.POST.copy()
        project_data['portfolio_id'] = portfolio_id
        form = ProjectForm(project_data)
        if form.is_valid():
            project = form.save(commit=False)
            project.portfolio = portfolio
            project.save()

            return redirect('portfolio-detail', portfolio_id)
    
    context = {'form': form}
    return render(request, 'portfolio_app/project_form.html', context)

def editProject(request, project_id):
    project = Project.objects.get(pk=project_id)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('portfolio-detail', project.portfolio.pk)
    
    context = {'form': form}
    return render(request, 'portfolio_app/edit_project.html', context)

def update_portfolio(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, instance=portfolio)
        if form.is_valid():
            form.save()
            return redirect('portfolio-detail', pk=portfolio_id)
    else:
        form = PortfolioForm(instance=portfolio)

    return render(request, 'portfolio_app/update_portfolio.html', {'form': form})

def delete_project(request, project_id):

    project = Project.objects.get(pk=project_id)
    if request.method == 'POST':
        project.delete()
        return redirect('portfolio-detail', project.portfolio.pk)

    return render(request, 'portfolio_app/delete_project.html', {'project': project})

def registerPage(request):

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='student')
            user.groups.add(group)
            student = Student.objects.create(user=user,)
            portfolio = Portfolio.objects.create()
            student.portfolio = portfolio
            student.save()

            messages.success(request, 'Account was created for ' + username)
            return redirect('login')
    
    context ={'form': form}
    return render(request, 'registration/register.html', context)


def userPage(request):
    student = request.user.student
    form = StudentForm(instance = student)
    print('student', student)
    portfolio = student.portfolio
    print(portfolio)
    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
    
    context = {'portfolios':portfolio, 'form':form}
    return render(request, 'portfolio_app/user.html', context)

Portfolio/portfolio_app/templates/portfolio_app/base_template.html
{% load static %}
{% load django_bootstrap5 %}


<!DOCTYPE html>
<html lang="en">
 <head>
   <title>UCCS CS Students</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   {% bootstrap_css %}
   {% bootstrap_javascript %}
   {% bootstrap_messages %}
  </head>


 <body>
   <div class="container-fluid">


     <!-- Navbar-->
     <nav class="navbar navbar-expand-lg bg-body-tertiary">
       <img src="{% static 'images/uccs_logo.gif' %}">
       <div class="container-fluid">
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <div class="navbar-nav">
             <!--  {% url 'index' %}  is defined in url path to dynamically create url -->
             <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
             <a class="nav-link" href="admin">Admin</a>
             <a class="nav-link" href="students">Students</a>
             <a class="nav-link" href="projects">Projects</a>
            {% if user.is_authenticated %}
             <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout {{user}}</a>
             {% else %}
              <a class="nav-link" href="{url 'login'}? next={{ request.path }}">Login</a>
              {% endif %}
           </div>
         </div>
       </div>
     </nav>


       <div class="col-sm-10">
         <!-- add block content from html template -->
         {% block content %}
         {% endblock %}
       </div>
     </div>
   </div>
 </body>
</html>

Portfolio/portfolio_app/templates/portfolio_app/delete_project.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
    <h1>Delete Project</h1>
    <p>Are you sure you want to delete the project "{{ project.title }}"?</p>
    <form action="{% url 'delete_project' project_id=project.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
    </form>
    <a href="{% url 'portfolio-detail' project.portfolio.id %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/edit_project.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
    <h1>Edit Project</h1>
    <form action="{% url 'edit_project' project_id=project.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/index.html
<!-- inherit from base.html-->
{% extends "portfolio_app/base_template.html" %}

<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Computer Science Portfolios</h1>

<h2>Active Portfolios</h2>

    <ul class="list-group">
        {% for i in studentActivePortfolios %} 
            <li class="list-group-item">Name: {{ i.name }} 
                <p><strong>Portfolio:{{ i.portfolio.title }} 
                    <a href="{{ i.portfolio.get_absolute_url }}" class="btn btn-primary">View</a>
                </strong></p> 
            </li> 
        {% endfor %} 
    </ul>  
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/portfolio_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}

<h1> Portfolio: {{ portfolio.title }} </h1>

<p><strong>Contact Email:</strong> {{ portfolio.contact_email }}</p>
<p><strong>Active:</strong> {% if portfolio.is_active %}Yes{% else %}No{% endif %}</p>
<p><strong>About:</strong> {{ portfolio.about }}</p>

<h2><strong>Projects:</strong></h2>
<ul>
  {% for project in portfolio.project_set.all %}
    <li>
      <strong>Title:</strong> {{ project.title }}<br>
      <a href="{{ project.get_absolute_url }}" class="btn btn-primary">View</a>
      <a href="{% url 'edit_project' project_id=project.id %}" class="btn btn-secondary" style="background-color: orange;">Edit</a> 
      <a href="{% url 'delete_project' project_id=project.id %}" class="btn btn-secondary" style="background-color:red;">Delete</a>

    </li>
  {% empty %}
    <li>No projects available.</li>
  {% endfor %}
</ul>

<a href="{% url 'create_project' portfolio.id %}" class="btn btn-primary">Create Project</a>

{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/project_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
    <h1>Project Details</h1>
    <p><strong>Title:</strong> {{ project.title }}</p>
    <p><strong>Description:</strong> {{ project.description }}</p>
    <p><strong>Portfolio:</strong> <a href="{{ project.portfolio.get_absolute_url }}">{{ project.portfolio.title }}</a></p>
    <p><strong>Student:</strong> <a href="{% url 'student-detail' project.portfolio.student.id %}">{{ project.portfolio.student.name }}</a></p>

{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/project_form.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
    <h1>Create Project</h1>
    <form action= '' method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_p }}
        
        <input type="submit" value="Create Project" style="background-color: blue; color: white; padding: 10px 20px; border: none; border-radius: 5px;">
        
    </form>

{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/project_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1> Projects </h1>
{% if project_list %}
<ul>
    {% for project in project_list %}
    <li>
        <a href="{% url 'project-detail' project.pk %}">{{ project.title }}</a>
    </li>

    {% endfor %}
</ul>
{% else %}
<p> There are no projects registered. </p>
{% endif %}
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/student_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}

<h1> Student: {{ student.name }} </h1>

<p><strong>Email:</strong> {{ student.email }}</p>
<p><strong>Major:</strong> {{ student.major }}</p>
<p><strong>Portfolio:</strong> <a>{{ student.portfolio.title }}</a></p>
<a href="{% url 'update_portfolio' portfolio_id=student.portfolio.id %}" class="btn btn-primary">Update Portfolio</a>

{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/student_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1> Student List </h1>
{% if student_list %}
<ul>
    {% for student in student_list %}
    <li>
        <a href="{{ student.get_absolute_url }}">{{ student.name }}</a>
    </li>

    {% endfor %}
</ul>
{% else %}
<p> There are no students registered. </p>
{% endif %}
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/update_portfolio.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
    <h1>Update Portfolio</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save Changes"style="background-color: blue; color: white; padding: 10px 20px; border: none; border-radius: 5px;">Save Changes</button>
    </form>
{% endblock %}

Portfolio/portfolio_app/templates/portfolio_app/user.html
{% extends 'portfolio_app/base_template.html' %}
{% block content %}
<h3>UCCS Student Profile</h3>
Welcome, {{user}}
 portfolio id: {{user.student.portfolio.id}}
 <p><strong>Portfolio:{{ user.student.portfolio.title }}
    <a class="btn btn-primary" href="{{ user.student.portfolio.get_absolute_url }}" role="button">View</a>
    <a class="btn btn-primary" href="{ % url 'update_portfolio' user.student.portfolio.id %}" role="button">Update</a>

 <h3>Student Information</h3>

 <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary" type="Submit" name="Update">
 </form>
</div>
{% endblock %}